--- InputBinContents  = {}
--- OutputBinContents = {}
--- system.print(wss_software.id .. ":tick(default) [" .. #InputBinContents .. "|" .. #OutputBinContents .."]")
--- LoadInputBinInventory()
--- LoadOutputBinInventory()
--- --- eof ---